# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 865540f4bbd4567a05bc68bee6978b5787e76b385f1112bbbe3de75178ba400361b56b3eb3ed9fbee61a125122410e2569bef5662e6f8410e10d3dcc48a311ff

test:
  secret_key_base: 95aa748f880d0e66f37a25244139c46ca88c783f2c7b1eaad0f5f715a306a02b79ffb0674e98ace148955e9f4d7853f0a29f09dffac22c3caebf8cb811cdf42a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
